ALZ.ConsultaProcessosTjmg.Web/ViewModels/Processo/ProcessoIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo
{
    public class ProcessoIndexViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Número do Processo")]
        public string NumeroProcesso { get; set; }
        [Display(Name = "Autor")]
        public string Autor { get; set; }
        [Display(Name = "Reu")]
        public string Reu { get; set; }
        [Display(Name = "Última Movimentação")]
        public string UltimaMovimentacao { get; set; }
        [Display(Name = "Data da Consulta")]
        public DateTime DataConsulta { get; set; }
        [Display(Name = "Situação")]
        public string Situacao { get; set; }
    }
}

ALZ.ConsultaProcessosTjmg.Web/ViewModels/Processo/ProcessoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo
{
    public class ProcessoViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O Número do Processo é obrigatório!")]
        [Display(Name = "Número do Processo")]
        public string NumeroProcesso { get; set; }

        [Required(ErrorMessage = "O nome do Autor é obrigatório!")]
        [Display(Name = "Autor")]
        public string Autor { get; set; }

        [Required(ErrorMessage = "O nome Reu é obrigatório!")]
        [Display(Name = "Reu")]
        public string Reu { get; set; }

        [Required(ErrorMessage = "A Última Movimentação é obrigatória!")]
        [Display(Name = "Última Movimentação")]
        public string UltimaMovimentacao { get; set; }

        [Required(ErrorMessage = "A Data da Consulta é obrigatória!")]
        [Display(Name = "Data da Consulta")]
        public DateTime DataConsulta { get; set; }

        [Required(ErrorMessage = "A Situação é obrigatória!")]
        [Display(Name = "Situação")]
        public string Situacao { get; set; }
    }
}

ALZ.ConsultaProcessosTjmg.Web/Controllers/ProcessosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ALZ.ConsultaProcessosTjmg.AcessoDados.Entity.Context;
using ALZ.ConsultaProcessosTjmg.Dominio;
using ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo;
using ALZ.ConsultaProcessosTjmg.Web.WebCrawler;
using AutoMapper;

namespace ALZ.ConsultaProcessosTjmg.Web.Controllers
{
    public class ProcessosController : Controller
    {
        private ConsultaProcessosDbContext db = new ConsultaProcessosDbContext();

        // GET: Processos
        public ActionResult Index()
        {
            return View(Mapper.Map<List<Processo>, List<ProcessoExibicaoViewModel>>(db.Processos.ToList()));
        }

        // GET: Processos/FiltrarPorNumero/5
        public ActionResult FiltrarPorNumero(string numeroProcesso)
        {
            return View();
        }

        // POST: Processos/Busca
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FiltrarPorNumero([Bind(Include = "NumeroProcesso")] ProcessoViewModel viewModel)
        {
            viewModel.NumeroProcesso = viewModel.NumeroProcesso.Replace("-", "").Replace(".", "");
            Processo processo = Mapper.Map<ProcessoViewModel, Processo>(viewModel);
            using (var context = new ConsultaProcessosDbContext())
            {
                var processoExistente = context.Processos
                                        .Where(p => p.NumeroProcesso.Equals(viewModel.NumeroProcesso))
                                        .FirstOrDefault();
                processo = processoExistente;
                if (processo == null)
                {
                    ViewBag.Mensagem = "Processo não encontrado!";
                    return View();
                }                
            }

            return RedirectToAction("Details", new { id = processo.Id });
        }

        // GET: Processos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Processo processo = db.Processos.Find(id);
            if (processo == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Processo, ProcessoExibicaoViewModel>(processo));
        }

        // GET: Processos/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Processos/Busca
        public ActionResult Busca()
        {
            return View();
        }

        // POST: Processos/Busca
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Busca([Bind(Include = "NumeroProcesso")] ProcessoViewModel viewModel)
        {
            viewModel.NumeroProcesso = viewModel.NumeroProcesso.Replace("-", "").Replace(".", "");
            Processo processo = Mapper.Map<ProcessoViewModel, Processo>(viewModel);
            using (var context = new ConsultaProcessosDbContext())
            {
                var processoExistente = context.Processos
                                        .Where(p => p.NumeroProcesso.Equals(viewModel.NumeroProcesso))
                                        .FirstOrDefault();
                if (processoExistente != null)
                {
                    Processo processoParaDeletar = db.Processos.Find(processoExistente.Id);
                    db.Processos.Remove(processoParaDeletar);
                    db.SaveChanges();
                }
            }
            Crawler crawler = new Crawler();
            processo = crawler.AcessaTjmg(viewModel.NumeroProcesso);
            db.Processos.Add(processo);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = processo.Id });
        }

        // POST: Processos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NumeroProcesso,Autor,Reu,UltimaMovimentacao,Situacao")] ProcessoViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Processo processo = Mapper.Map<ProcessoViewModel, Processo>(viewModel);
                processo.DataConsulta = DateTime.Now;
                db.Processos.Add(processo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Processos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Processo processo = db.Processos.Find(id);
            if (processo == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Processo, ProcessoViewModel>(processo));
        }

        // POST: Processos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NumeroProcesso,Autor,Reu,UltimaMovimentacao,DataConsulta,Situacao")] ProcessoViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Processo processo = Mapper.Map<ProcessoViewModel, Processo>(viewModel);
                db.Entry(processo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Processos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Processo processo = db.Processos.Find(id);
            if (processo == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Processo, ProcessoExibicaoViewModel>(processo));
        }

        // POST: Processos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Processo processo = db.Processos.Find(id);
            db.Processos.Remove(processo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Busca.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoViewModel

@{

    ViewBag.Title = "Buscar Processos";
}

<h2>Buscar Processo no TJMG</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h4>Digite um Número de Processo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProcesso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProcesso, new { htmlAttributes = new { @class = "mixed form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroProcesso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Create.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoViewModel

@{
    ViewBag.Title = "Criar Processos";
}

<h2>Criar</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Processo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProcesso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProcesso, new { htmlAttributes = new { @class = "mixed form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroProcesso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UltimaMovimentacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UltimaMovimentacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UltimaMovimentacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Situacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Delete.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoExibicaoViewModel

@{
    ViewBag.Title = "Deletar Processos";
}

<h2>Deletar</h2>

<h3>Tem certeza de que deseja excluir isso?</h3>

<br />

<div>
    <h4>Processo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroProcesso)
        </dt>

        <dd class="mixed">
            @Html.DisplayFor(model => model.NumeroProcesso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UltimaMovimentacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimaMovimentacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataConsulta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataConsulta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Situacao)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para Lista", "Index")
        </div>
    }
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Details.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoExibicaoViewModel

@{
    ViewBag.Title = "Detalhes Processo";
}

<h2>Detalhes</h2>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

<div>
    <h4>Processo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroProcesso)
        </dt>

        <dd class="mixed">
            @Html.DisplayFor(model => model.NumeroProcesso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UltimaMovimentacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimaMovimentacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataConsulta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataConsulta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Situacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para Lista", "Index")
</p>

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Edit.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoViewModel

@{
    ViewBag.Title = "Editar Processos";
}

<h2>Editar Processo</h2>

@using (Html.BeginForm("Edit", "Processos", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "teste", id = "teste2" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h4>Processo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProcesso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProcesso, new { htmlAttributes = new { @class = "mixed form-control"} })
                @Html.ValidationMessageFor(model => model.NumeroProcesso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UltimaMovimentacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UltimaMovimentacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UltimaMovimentacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataConsulta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataConsulta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataConsulta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Situacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar Alterações" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
        $("#teste2").submit(function (event) {
            $('.mixed').cleanVal();
        });
    </script>
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/FiltrarPorNumero.cshtml
@model ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoViewModel

@{

    ViewBag.Title = "Filtrar Processos";
}

<h2>Filtrar Processo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h4>Digite um Número de Processo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProcesso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProcesso, new { htmlAttributes = new { @class = "mixed form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroProcesso, "", new { @class = "text-danger" })
            </div>
        </div>
        @ViewBag.Mensagem
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

ALZ.ConsultaProcessosTjmg.Web/Views/Processos/Index.cshtml
@model IEnumerable<ALZ.ConsultaProcessosTjmg.Web.ViewModels.Processo.ProcessoExibicaoViewModel>

@{
    ViewBag.Title = "Index Processos";
}

<h2>Processos Cadastrados</h2>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.mixed').mask('0000000-00.0000.0.00.0000');
        });
    </script>
}

<br />

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NumeroProcesso)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UltimaMovimentacao)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.DataConsulta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Situacao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="mixed">
                @Html.DisplayFor(modelItem => item.NumeroProcesso)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UltimaMovimentacao)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.DataConsulta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Situacao)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>